### 1

In [30]:
import numpy as np

In [31]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [32]:
np.reshape(a,(3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
np.reshape(a,(4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [34]:
np.reshape(a,(1,12))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
np.reshape(a,(12,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [38]:
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.reshape(a,(4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [42]:
np.reshape(a,(-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [43]:
np.reshape(a,(-1,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
np.reshape(a,(-1,12))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [45]:
np.reshape(a,(12,-1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - да

### 2

In [49]:
a = np.random.sample((3,4))
b = np.array(a,dtype = float)
b

array([[0.62145638, 0.15032423, 0.71294942, 0.0789653 ],
       [0.71750058, 0.81872333, 0.9002931 , 0.61606956],
       [0.81697129, 0.72353729, 0.64219825, 0.35845113]])

In [50]:
b = b.flatten()

In [51]:
b

array([0.62145638, 0.15032423, 0.71294942, 0.0789653 , 0.71750058,
       0.81872333, 0.9002931 , 0.61606956, 0.81697129, 0.72353729,
       0.64219825, 0.35845113])

### 3

In [53]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [55]:
b = np.reshape(a,(1,10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### 4

In [73]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [74]:

b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [75]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
v.size

10

### 5

In [77]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
A = np.reshape(a,(4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [80]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [81]:
B.shape

(4, 4)

вычислить обратную матрицу для матрицы B получится, потому что она квадратная


### 6

In [82]:
c = np.random.randint(0,16,16)
c

array([ 5, 10,  4, 13,  2, 10,  6,  9, 13, 12,  6,  1,  1,  8,  4,  9])

In [85]:
C = c.reshape((4,4))

In [86]:
C

array([[ 5, 10,  4, 13],
       [ 2, 10,  6,  9],
       [13, 12,  6,  1],
       [ 1,  8,  4,  9]])

In [87]:
C=C*10

In [88]:
C

array([[ 50, 100,  40, 130],
       [ 20, 100,  60,  90],
       [130, 120,  60,  10],
       [ 10,  80,  40,  90]])

In [89]:
D = C+B
D

array([[ 55, 114,  63, 162],
       [ 34, 150, 146, 212],
       [153, 206, 209, 222],
       [ 42, 202, 252, 392]])

### определитель D:

In [90]:
np.linalg.det(D)

101059200.00000006

###  ранг D:

In [91]:
np.linalg.matrix_rank(D)

4

### обратная матрица для D:

In [92]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00702717, -0.02246604,  0.00765413,  0.00491118],
       [ 0.00196716,  0.03029986, -0.0032195 , -0.01537633],
       [-0.01641691,  0.00192204,  0.00461472,  0.00313163],
       [ 0.00878713, -0.01444223, -0.00212766,  0.00793515]])

In [96]:
D_inv[(D_inv > 0) == 1 and (D_inv < 0) == 0]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()